-   repo: https://git.uyunsoft.cn/contrib/pre-commit-hooks.git
    sha: v0.8.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
        args:
        - --max-line-length=100
-   repo: https://git.uyunsoft.cn/contrib/pre-commit-yapf.git
    sha: v0.16.2
    hooks:
    -   id: yapf
