package uyun.bat.web.impl.common.util;

import com.alibaba.druid.support.json.JSONUtils;
import uyun.bat.web.impl.common.entity.TenantConstants;

import java.util.Map;

/**
 * 收集目前monitor能监控的集成
 */
public abstract class IntegrationUtil {

	// 收集目前monitor能监控的集成
	public static final String integrations = "{\"apache\": \"apache\",\"hdfs\": \"hdfs\",\"mysql\": \"mysql\",\"nagios\": \"nagios\",\"zookeeper\": \"zookeeper\",\"kafka\": \"kafka\",\"tomcat\": \"tomcat\",\"cassandra\": \"cassandra\",\"activemq\": \"activemq\",\"system\": \"system\",\"rabbitmq\": \"rabbitmq\",\"openstack\": \"openstack\",\"mongodb\": \"mongodb\",\"redis\": \"redis\",\"业务\": \"业务\",\"vsphere\": \"vsphere\",\"memcache\": \"memcache\",\"nginx\": \"nginx\",\"oracle\": \"oracle\",\"docker\": \"docker\",\"ntp\": \"ntp\",\"dm\": \"dm\",\"iis\": \"iis\",\"jboss\": \"jboss\",\"jenkins\": \"jenkins\",\"mesos\": \"mesos\",\"mapreduce\": \"mapreduce\",\"elasticsearch\": \"elasticsearch\",\"dellequallogic\": \"dell_equallogic\",\"emcvnx\": \"emc_vnx\",\"hp3par\": \"hp_3par\",\"hpeva\": \"hp_eva\",\"huawei\": \"huawei_device\",\"netappfas\": \"netapp_fas_smis\",\"emcsymm\": \"emc_symm\",\"emccelerra\": \"emc_celerra\",\"ibmsvc\": \"ibm_svc\",\"ibmds\": \"ibm_ds\",\"jvm\": \"java\",\"db2\": \"db2\",\"cli\": \"cli\",\"exchange\": \"exchange\",\"haproxy\": \"haproxy\",\"hypervisor\": \"hypervisor\",\"ibmmq\": \"ibmmq\",\"icmp\": \"icmp\",\"informix\": \"informix\",\"ipmi\": \"ipmi\",\"kubernetes\": \"kubernetes\",\"mssql\": \"mssql\",\"netapp\": \"netapp\",\"netdevice\": \"netdevice\",\"postgresql\": \"postgresql\",\"postfix\": \"postfix\",\"resin\": \"resin\",\"ssh\": \"ssh\",\"service_avaliable\": \"service_avaliable\",\"shentong\": \"shentong\",\"snmp\": \"snmp\",\"sqlserver\": \"sqlserver\",\"sybase\": \"sybase\",\"tongweb\": \"tongweb\",\"tux\": \"tuxedo\",\"vmware\": \"vmware\",\"weblogic\": \"weblogic\",\"websphere\": \"websphere\",\"domino\": \"domino\",\"gae\": \"Google App Engine\",\"gcp\": \"Google Cloud Platform\",\"aws\": \"Amazon Web Services\",\"new_relic\": \"New Relic\",\"ansible\": \"ansible\",\"lighttpd\": \"lighttpd\",\"etcd\": \"etcd\",\"azure\": \"azure\",\"ceph\": \"ceph\",\"gunicorn\": \"gunicorn\",\"yarn\": \"yarn\",\"varnish\": \"varnish\",\"supervisord\": \"supervisord\",\"solr\": \"solr\",\"riakcs\": \"riakcs\",\"pingdom\": \"pingdom\",\"pgbouncer\": \"pgbouncer\",\"marathon\": \"marathon\",\"gearman\": \"gearman\",\"fluentd\": \"fluentd\",\"fastly\": \"fastly\",\"dyn\": \"dyn\",\"desk\": \"desk\",\"chef\": \"chef\",\"consul\": \"consul\",\"airbrake\": \"airbrake\",\"couchbase\": \"couchbase\",\"couchdb\": \"couchdb\",\"riak\": \"riak\",\"tokumx\": \"tokumx\",\"memcached\": \"memcached\",\"maprecude\": \"maprecude\",\"kong\": \"kong\",\"go_expvar\": \"Go Expvar\",\"spark\": \"spark\",\"btrfs\": \"btrfs\",\"node\": \"express\"}";
	public static final Map<String, String> inMap = (Map<String, String>) JSONUtils.parse(integrations);
	// 特殊处理一些与integration字段不符合的指标,方便后续按integration分类
	// TODO integration为cli，cacti的system开头指标暂时一起放在system里面了
	public static final String metric_to_integration = "{\"postgre.tablespace.size\": \"postgresql\",\"sqlserver.data.size\": \"mssql\",\"sqlserver.db.size\": \"mssql\",\"sqlserver.index.size\": \"mssql\",\"sqlserver.jdbc.file.size\": \"mssql\",\"sqlserver.jdbc.max.capacity.size\": \"mssql\",\"sqlserver.retained.size\": \"mssql\",\"sqlserver.session.cpu\": \"mssql\",\"sqlserver.session.ram\": \"mssql\",\"sqlserver.unassigned.size\": \"mssql\",\"sqlserver.unused.size\": \"mssql\",\"system.cpu.num\": \"vmware\",\"oracle.pga.freeable\": \"snmp\",\"system.disk.partition.space.total\": \"snmp\",\"system.disk.partition.space.unused\": \"snmp\",\"system.disk.partition.use.pct_usage\": \"snmp\",\"system.mem.total.size\": \"snmp\",\"system.process.cpu.total_used\": \"snmp\",\"websphere.channel.path.send.interval\": \"ibmmq\",\"websphere.channel.per_sec\": \"ibmmq\",\"websphere.channel.receive.per_sec\": \"ibmmq\",\"websphere.channel.start.path.acts.count\": \"ibmmq\",\"websphere.mq.queue.message.byte_max\": \"ibmmq\",\"websphere.mq.queue.message.count\": \"ibmmq\",\"websphere.mq.queue.open.in.count\": \"ibmmq\",\"websphere.mq.queue.open.out.count\": \"ibmmq\",\"dns.response_time\": \"service_avaliable\",\"ftp.response_time\": \"service_avaliable\",\"http.response_time\": \"service_avaliable\",\"https.response_time\": \"service_avaliable\",\"pop3.response_time\": \"service_avaliable\",\"smtp.response_time\": \"service_avaliable\",\"tcp.response_time\": \"service_avaliable\",\"ram.net.mem.used\": \"netdevice\",\"system.in.frame_rate.error.frame_rate\": \"netdevice\",\"system.no_unicast.in.frame_rate\": \"netdevice\",\"system.no_unicast.out.frame_rate\": \"netdevice\",\"system.out.frame_rate.error.frame_rate\": \"netdevice\",\"system.unicast.in.frame_rate\": \"netdevice\",\"system.unicast.out.frame_rate\": \"netdevice\",\"systen.port.in.frame_rate\": \"netdevice\",\"systen.port.out.frame_rate\": \"netdevice\",\"temperature.net.device.temperature\": \"netdevice\",\"system.disk.btrfs.free\": \"btrfs\",\"system.disk.btrfs.total\": \"btrfs\",\"system.disk.btrfs.usage\": \"btrfs\",\"system.disk.btrfs.used\": \"btrfs\",\"sftp.response_time\": \"ssh\",\"netapp.fts.space_used.pct\": \"netapp_fas_snmp\",\"netapp.powersupply.fault.num\": \"netapp_fas_snmp\",\"system.cpu.used.pct\": \"netapp_fas_snmp\",\"system.cpu.interrupted.pct\": \"netapp_fas_snmp\"}";
	public static final Map<String, String> changeMap = (Map<String, String>) JSONUtils.parse(metric_to_integration);
}
